### ISSUE TITLE
运行时出错

### ISSUE THREAD

**Issue by linhaibo123** [bojone/unsupervised-text-generation#1]
苏神你好，直接下载nezha的预训练模型，进行预测的时候，报输入错误，
我看了下，输入的时候feed_input_name 要求是：['Input-Token', 'Input-Segment']
但是输入的x是[[ 101 2408 2336 5401 7608 2458 2391]]，维度不对应，这个要如何修改

```
Sampling:   5%|▍         | 6/128 [10:27<3:32:36, 104.56s/it]
Traceback (most recent call last):
  File "/data/pycharm-2020.3.5/plugins/python/helpers/pydev/pydevd.py", line 1477, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/data/pycharm-2020.3.5/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/linhb/下载/unsupervised-text-generation-main/gpt_cgmh.py", line 137, in <module>
    ids = TopCandidates(new_token_ids, i)
  File "/home/linhb/下载/unsupervised-text-generation-main/gpt_cgmh.py", line 55, in TopCandidates
    probas = model.predict(token_ids)[0, -1]
  File "/home/linhb/anaconda3/envs/tf1/lib/python3.7/site-packages/keras/engine/training.py", line 1441, in predict
    x, _, _ = self._standardize_user_data(x)
  File "/home/linhb/anaconda3/envs/tf1/lib/python3.7/site-packages/keras/engine/training.py", line 579, in _standardize_user_data
    exception_prefix='input')
  File "/home/linhb/anaconda3/envs/tf1/lib/python3.7/site-packages/keras/engine/training_utils.py", line 109, in standardize_input_data
    str(len(data)) + ' arrays: ' + str(data)[:200] + '...')
ValueError: Error when checking model input: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 2 array(s), but instead got the following list of 1 arrays: [array([[ 101, 2408, 2336, 5401, 7608, 2458, 2391]])]...
```

**Comment by linhaibo123** [comment]
解决了，bert4keras 版本太低了
